// <auto-generated />
using System;
using Bigbangassess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bigbangassess.Migrations
{
    [DbContext(typeof(HotelRoomContext))]
    partial class HotelRoomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bigbangassess.Models.Customer", b =>
                {
                    b.Property<int>("custId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("custId"));

                    b.Property<string>("custName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("hotelId")
                        .HasColumnType("int");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("custId");

                    b.HasIndex("hotelId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("Bigbangassess.Models.Hotel", b =>
                {
                    b.Property<int>("hotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("hotelId"));

                    b.Property<string>("hotelAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotelContact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotelLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hotelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("hotelRatings")
                        .HasColumnType("int");

                    b.HasKey("hotelId");

                    b.ToTable("hotels");
                });

            modelBuilder.Entity("Bigbangassess.Models.Room", b =>
                {
                    b.Property<int>("roomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roomId"));

                    b.Property<string>("Availability")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PricePerDay")
                        .HasColumnType("int");

                    b.Property<int?>("hotelId")
                        .HasColumnType("int");

                    b.Property<string>("roomType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roomId");

                    b.HasIndex("hotelId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("Bigbangassess.Models.Staff", b =>
                {
                    b.Property<int>("staffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("staffId"));

                    b.Property<int?>("hotelId")
                        .HasColumnType("int");

                    b.Property<string>("staffGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("staffId");

                    b.HasIndex("hotelId");

                    b.ToTable("staffs");
                });

            modelBuilder.Entity("Bigbangassess.Models.Customer", b =>
                {
                    b.HasOne("Bigbangassess.Models.Hotel", null)
                        .WithMany("Customer")
                        .HasForeignKey("hotelId");
                });

            modelBuilder.Entity("Bigbangassess.Models.Room", b =>
                {
                    b.HasOne("Bigbangassess.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("hotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Bigbangassess.Models.Staff", b =>
                {
                    b.HasOne("Bigbangassess.Models.Hotel", "Hotel")
                        .WithMany("Staffs")
                        .HasForeignKey("hotelId");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Bigbangassess.Models.Hotel", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Rooms");

                    b.Navigation("Staffs");
                });
#pragma warning restore 612, 618
        }
    }
}
